#/etc/proftpd/proftpd.conf

# Include DSO modules
Include /etc/proftpd/modules.conf

# Enable IPv6 support
UseIPv6 on

# Disable ident lookups
<IfModule mod_ident.c>
  IdentLookups off
</IfModule>

# Server settings
ServerName "Debian"
ServerType standalone
DeferWelcome off
DefaultServer on
ShowSymlinks on

# Timeout settings
TimeoutNoTransfer 600
TimeoutStalled 600
TimeoutIdle 1200

# Display settings
DisplayLogin welcome.msg
DisplayChdir .message true
ListOptions "-l"

# Deny filtering
DenyFilter \*.*/

# Set the default root directory for all users
DefaultRoot /var/www/followthefacts.org

# Port configuration
Port 21

# Authentication settings
AuthUserFile /etc/proftpd/ftpd.passwd
AuthOrder mod_auth_file.c
RequireValidShell off