#!/bin/bash

pipinstall() {
    echo ""
    echo "Installing $1"
    pip3 install "$1" 2>/dev/null || echo "Error installing $1, but continuing..."
}


pipinstall PyYAML
pipinstall pyobjc-framework-AppKit
pipinstall arrow
pipinstall astor
pipinstall audioio
pipinstall auditSQL
pipinstall binaryornot
pipinstall beautifulsoup4
pipinstall bz2file
pipinstall chardet
pipinstall clockwork
pipinstall colorama
pipinstall config_helper
pipinstall pycryptodome
pipinstall cryptography
pipinstall cssselect
pipinstall opencv-python-headless
pipinstall datefinder
pipinstall dateutils
pipinstall digitalio
pipinstall dill
pipinstall dnspython
pipinstall python-docx
pipinstall docx_utils
pipinstall docx2txt
pipinstall encryptedpickle
pipinstall exif-compare
pipinstall fileBackup
pipinstall findKey
pipinstall Flask
pipinstall ftputil
pipinstall geopy
pipinstall getmac
pipinstall gh-md-to-html
pipinstall pygobject
pipinstall glob2
pipinstall google-auth-oauthlib
pipinstall gspread
pipinstall gTTS
pipinstall icalendar
pipinstall ics
pipinstall IMDbPY
pipinstall importlib-metadata
pipinstall instaloader
pipinstall IP2Location
pipinstall ipaddress
pipinstall jsonschema
pipinstall keyboard
pipinstall 2to3
pipinstall 3to2
pipinstall lorem
pipinstall lxml
pipinstall movieTitle
pipinstall mp3-tagger
pipinstall mpu
pipinstall native-web-app
pipinstall netaddr
pipinstall nltk
pipinstall num2words
pipinstall numpy
pipinstall oauth2client
pipinstall odfpy
pipinstall openai
pipinstall pyOpenSSL
pipinstall pandas
pipinstall paramiko
pipinstall pbkdf2
pipinstall pgeocode
pipinstall phonenumbers
pipinstall piexif
pipinstall Pillow
pipinstall pinax
pipinstall progressbar2
pipinstall psutil
pipinstall pulseio
pipinstall py2exe
pipinstall pyAesCrypt
pipinstall pyautogui
pipinstall pydub
pipinstall pygame
pipinstall pykeyboard
pipinstall pylnk
pipinstall pymongo
pipinstall pymysql
pipinstall pynput
pipinstall pyodbc
pipinstall PyPDF2
pipinstall pyperclip
pipinstall PyQt4
pipinstall pytesseract
pipinstall pytz
pipinstall random-tool
pipinstall regex
pipinstall requests
pipinstall rightthumb
pipinstall schedule
pipinstall scrapy
pipinstall selenium
pipinstall webdriver-manager
pipinstall SimpleGUICS2Pygame
pipinstall simplejson
pipinstall smtplib
pipinstall SpeechRecognition
pipinstall speedtest-cli
pipinstall sshtunnel
pipinstall stickytape
pipinstall tldextract
pipinstall tqdm
pipinstall twilio
pipinstall txtBackup2
pipinstall urlextract
pipinstall usaddress
pipinstall uuid
pipinstall watchdog
pipinstall webbrowser
pipinstall wget
pipinstall whois
pipinstall pywin32
pipinstall youtube-dl
