@echo off

call:pipinstall PyYAML
call:pipinstall pyobjc-framework-AppKit
call:pipinstall arrow
call:pipinstall astor
call:pipinstall audioio
call:pipinstall auditSQL
call:pipinstall binaryornot
call:pipinstall beautifulsoup4
call:pipinstall bz2file
call:pipinstall chardet
call:pipinstall clockwork
call:pipinstall colorama
call:pipinstall config_helper
call:pipinstall pycryptodome
call:pipinstall cryptography
call:pipinstall cssselect
call:pipinstall opencv-python-headless
call:pipinstall datefinder
call:pipinstall dateutils
call:pipinstall digitalio
call:pipinstall dill
call:pipinstall dnspython
call:pipinstall python-docx
call:pipinstall docx_utils
call:pipinstall docx2txt
call:pipinstall encryptedpickle
call:pipinstall exif-compare
call:pipinstall fileBackup
call:pipinstall findKey
call:pipinstall Flask
call:pipinstall ftputil
call:pipinstall geopy
call:pipinstall getmac
call:pipinstall gh-md-to-html
call:pipinstall pygobject
call:pipinstall glob2
call:pipinstall google-auth-oauthlib
call:pipinstall gspread
call:pipinstall gTTS
call:pipinstall icalendar
call:pipinstall ics
call:pipinstall IMDbPY
call:pipinstall importlib-metadata
call:pipinstall instaloader
call:pipinstall IP2Location
call:pipinstall ipaddress
call:pipinstall jsonschema
call:pipinstall keyboard
call:pipinstall 2to3
call:pipinstall 3to2
call:pipinstall lorem
call:pipinstall lxml
call:pipinstall movieTitle
call:pipinstall mp3-tagger
call:pipinstall mpu
call:pipinstall native-web-app
call:pipinstall netaddr
call:pipinstall nltk
call:pipinstall num2words
call:pipinstall numpy
call:pipinstall oauth2client
call:pipinstall odfpy
call:pipinstall openai
call:pipinstall pyOpenSSL
call:pipinstall pandas
call:pipinstall paramiko
call:pipinstall pbkdf2
call:pipinstall pgeocode
call:pipinstall phonenumbers
call:pipinstall piexif
call:pipinstall Pillow
call:pipinstall pinax
call:pipinstall progressbar2
call:pipinstall psutil
call:pipinstall pulseio
call:pipinstall py2exe
call:pipinstall pyAesCrypt
call:pipinstall pyautogui
call:pipinstall pydub
call:pipinstall pygame
call:pipinstall pykeyboard
call:pipinstall pylnk
call:pipinstall pymongo
call:pipinstall pymysql
call:pipinstall pynput
call:pipinstall pyodbc
call:pipinstall PyPDF2
call:pipinstall pyperclip
call:pipinstall PyQt4
call:pipinstall pytesseract
call:pipinstall pytz
call:pipinstall random-tool
call:pipinstall regex
call:pipinstall requests
call:pipinstall rightthumb
call:pipinstall schedule
call:pipinstall scrapy
call:pipinstall selenium
call:pipinstall webdriver-manager
call:pipinstall SimpleGUICS2Pygame
call:pipinstall simplejson
call:pipinstall smtplib
call:pipinstall SpeechRecognition
call:pipinstall speedtest-cli
call:pipinstall sshtunnel
call:pipinstall stickytape
call:pipinstall tldextract
call:pipinstall tqdm
call:pipinstall twilio
call:pipinstall txtBackup2
call:pipinstall urlextract
call:pipinstall usaddress
call:pipinstall uuid
call:pipinstall watchdog
call:pipinstall webbrowser
call:pipinstall wget
call:pipinstall whois
call:pipinstall pywin32
call:pipinstall youtube-dl
goto:eof
:pipinstall
echo.
echo installing %1
pip3 install %1 2>nul || echo Error installing %1, but continuing...
goto:eof
