#!/bin/bash
pip3 install PyYAML
pip3 install pyobjc-framework-AppKit
pip3 install arrow
pip3 install astor
pip3 install audioio
pip3 install auditSQL
pip3 install binaryornot
pip3 install beautifulsoup4
pip3 install bz2file
pip3 install chardet
pip3 install clockwork
pip3 install colorama
pip3 install config_helper
pip3 install pycryptodome
pip3 install cryptography
pip3 install cssselect
pip3 install opencv-python-headless
pip3 install datefinder
pip3 install dateutils
pip3 install digitalio
pip3 install dill
pip3 install dnspython
pip3 install python-docx
pip3 install docx_utils
pip3 install docx2txt
pip3 install encryptedpickle
pip3 install exif-compare
pip3 install fileBackup
pip3 install findKey
pip3 install Flask
pip3 install ftputil
pip3 install geopy
pip3 install getmac
pip3 install gh-md-to-html
pip3 install pygobject
pip3 install glob2
pip3 install google-auth-oauthlib
pip3 install gspread
pip3 install gTTS
pip3 install icalendar
pip3 install ics
pip3 install IMDbPY
pip3 install importlib-metadata
pip3 install instaloader
pip3 install IP2Location
pip3 install ipaddress
pip3 install jsonschema
pip3 install keyboard
pip3 install 2to3
pip3 install 3to2
pip3 install lorem
pip3 install lxml
pip3 install movieTitle
pip3 install mp3-tagger
pip3 install mpu
pip3 install native-web-app
pip3 install netaddr
pip3 install nltk
pip3 install num2words
pip3 install numpy
pip3 install oauth2client
pip3 install odfpy
pip3 install openai
pip3 install pyOpenSSL
pip3 install pandas
pip3 install paramiko
pip3 install pbkdf2
pip3 install pgeocode
pip3 install phonenumbers
pip3 install piexif
pip3 install Pillow
pip3 install pinax
pip3 install progressbar2
pip3 install psutil
pip3 install pulseio
pip3 install py2exe
pip3 install pyAesCrypt
pip3 install pyautogui
pip3 install pydub
pip3 install pygame
pip3 install pykeyboard
pip3 install pylnk
pip3 install pymongo
pip3 install pymysql
pip3 install pynput
pip3 install pyodbc
pip3 install PyPDF2
pip3 install pyperclip
pip3 install PyQt4
pip3 install pytesseract
pip3 install pytz
pip3 install random-tool
pip3 install regex
pip3 install requests
pip3 install rightthumb
pip3 install schedule
pip3 install scrapy
pip3 install selenium
pip3 install webdriver-manager
pip3 install SimpleGUICS2Pygame
pip3 install simplejson
pip3 install smtplib
pip3 install SpeechRecognition
pip3 install speedtest-cli
pip3 install sshtunnel
pip3 install stickytape
pip3 install tldextract
pip3 install tqdm
pip3 install twilio
pip3 install txtBackup2
pip3 install urlextract
pip3 install usaddress
pip3 install uuid
pip3 install watchdog
pip3 install webbrowser
pip3 install wget
pip3 install whois
pip3 install pywin32
pip3 install youtube-dl
