@echo off
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call p. vps-clip-sync %*
call clip %*
