@echo off
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise

call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise

call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise

call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise

call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call p KeyWise
call hk.l
 
