@echo off
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys

call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys

call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys

call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys

call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call p hotkeys
call hk.l
 
