instructions = {

# ## {R2D2919B742E} ##
# ###########################################################################
# What if magic existed?
# What if a place existed where your every thought and dream come to life.
# There is only one catch: it has to be written down.
# Such a place exists, it is called programming.
#    - Scott Taylor Reph, RightThumb.com
# ###########################################################################
# ## {C3P0D40fAe8B} ##

	'characters': [{
						'id': 0,
						'char': '[',
						'print': '[',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': 0,
							'is': ['list'],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 1,
							'isOpen': 1,
							'hasClose': 1
						}]
					}, {
						'id': 1,
						'char': ']',
						'print': ']',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': 0,
							'is': ['list'],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 1,
							'isOpen': 0,
							'hasClose': 1
						}]
					}, {
						'id': 2,
						'char': '(',
						'print': '(',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': 1,
							'is': ['tuple', 'function'],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 1,
							'isOpen': 1,
							'hasClose': 1
						}]
					}, {
						'id': 3,
						'char': ')',
						'print': ')',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': 1,
							'is': ['tuple', 'function'],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 1,
							'isOpen': 0,
							'hasClose': 1
						}]
					}, {
						'id': 4,
						'char': '{',
						'print': '{',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': 2,
							'is': ['dict'],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 1,
							'isOpen': 1,
							'hasClose': 1
						}]
					}, {
						'id': 5,
						'char': '}',
						'print': '}',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': 2,
							'is': ['dict'],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 1
						}]
					}, {
						'id': 6,
						'char': '/',
						'print': '/',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': [],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}, {
							'code': 'javascript',
							'groupID': False,
							'is': ['inline comment'],
							'set': [6],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 1,
							'hasClose': 0
						}, {
							'code': 'javascript',
							'groupID': 3,
							'is': ['comment'],
							'set': [7],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 1,
							'hasClose': 1
						}]
					}, {
						'id': 7,
						'char': '*',
						'print': '*',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': [],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}, {
							'code': 'javascript',
							'groupID': 3,
							'is': ['comment'],
							'set': [6],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 1
						}]
					}, {
						'id': 8,
						'char': '\n',
						'print': _v.slash+'n',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': ['carage', 'end'],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}, {
							'code': 'javascript',
							'groupID': False,
							'is': ['carage', 'whitespace'],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}]
					}, {
						'id': 9,
						'char': ' ',
						'print': ' ',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': ['whitespace'],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}]
					}, {
						'id': 10,
						'char': '\t',
						'print': _v.slash+'t',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': ['whitespace'],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}]
					}, {
						'id': 11,
						'char': "'",
						'print': "'",
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': ['quote'],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 1,
							'hasClose': 1
						}]
					}, {
						'id': 12,
						'char': '"',
						'print': '"',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': ['quote'],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 1,
							'hasClose': 1
						}, {
							'code': 'python',
							'groupID': False,
							'is': ['quote'],
							'escape': [],
							'rules': [],
							'nest': 0,
							'set': [12, 12],
							'isOpen': 1,
							'hasClose': 1
						}]
					}, {
						'id': 13,
						'char': '=',
						'print': '=',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': ['equals'],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}]
					}, {
						'id': 14,
						'char': ';',
						'print': ';',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': [],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}, {
							'code': 'javascript',
							'groupID': False,
							'is': ['end'],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}]
					}, {
						'id': 15,
						'char': ':',
						'print': ':',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': [],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}]
					}, {
						'id': 16,
						'char': '#',
						'print': '#',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': [],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}, {
							'code': 'python',
							'groupID': False,
							'is': ['inline comment'],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 1,
							'hasClose': 0
						}]
					}, {
						'id': 17,
						'char': ',',
						'print': ',',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': [],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}]
					}, {
						'id': 18,
						'char': _v.slash,
						'print': _v.slash,
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': [],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}]
					}, {
						'id': 19,
						'char': '<',
						'print': '<',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': [],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}]
					}, {
						'id': 20,
						'char': '>',
						'print': '>',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': [],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}]
					}, {
						'id': 21,
						'char': '.',
						'print': '.',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': [],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
						}]
					}, {
						'id': 22,
						'char': '+',
						'print': '+',
						'database': [],
						'languages': [{
							'code': 'global',
							'groupID': False,
							'is': [],
							'set': [],
							'escape': [],
							'rules': [],
							'nest': 0,
							'isOpen': 0,
							'hasClose': 0
				}]
		}],


	'action': [{
				'id': 0,
				'description': 'function',
				'code': 'python',
				'test': ['def'],
				'specific': True,
				'caseStrict': False,
				'start': True,
				'type': [0],
				'rules': [0]
			}, {
				'id': 1,
				'description': 'class',
				'code': 'python',
				'test': ['class'],
				'specific': True,
				'caseStrict': False,
				'start': True,
				'type': [1],
				'rules': [1]
			}, {
				'id': 2,
				'description': 'function',
				'code': 'javascript',
				'test': ['function'],
				'specific': True,
				'caseStrict': False,
				'start': True,
				'type': [0],
				'rules': [2]
			}, {
				'id': 6,
				'description': 'variable',
				'code': 'python',
				'test': ['abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-.'],
				'specific': False,
				'caseStrict': False,
				'start': True,
				'type': [3],
				'rules': [2]
			}, {
				'id': 4,
				'description': 'variable',
				'code': 'javascript',
				'test': ['var'],
				'specific': True,
				'caseStrict': False,
				'start': True,
				'type': [3],
				'rules': [3]
			}, {
				'id': 5,
				'description': 'import',
				'code': 'python',
				'test': ['import'],
				'specific': True,
				'caseStrict': False,
				'start': True,
				'type': [3],
				'rules': [5]
			}, {
				'id': 6,
				'description': 'variable',
				'code': 'javascript',
				'test': ['abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-'],
				'specific': False,
				'caseStrict': False,
				'start': True,
				'type': [3],
				'rules': [3]
			}, {
				'id': 7,
				'description': 'orphans',
				'code': 'global',
				'test': [0, 2, 4, ['quote'], 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-'],
				'specific': False,
				'caseStrict': False,
				'start': True,
				'type': [3],
				'rules': [6]
			}, {
				'id': 8,
				'description': 'command',
				'code': 'javascript',
				'test': ['abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-.'],
				'specific': False,
				'caseStrict': False,
				'start': True,
				'type': [3],
				'rules': [7]
		}],


	'type': [{
				'id': 0,
				'name': 'function'
			}, {
				'id': 1,
				'name': 'class'
			}, {
				'id': 2,
				'name': 'label'
			}, {
				'id': 3,
				'name': 'variable'
			}, {
				'id': 4,
				'name': 'command'
			}],


	'rules': [{
				'id': 0,
				'code': 'python',
				'description': 'function',
				'pattern': [{
					'required': True,
					'specific': True,
					'ifLast': False,
					'test': ['def']
				}, {
					'required': True,
					'specific': False,
					'ifLast': False,
					'test': ['abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-']
				}, {
					'required': True,
					'specific': True,
					'ifLast': False,
					'test': [2]
				}, {
					'required': True,
					'specific': True,
					'ifLast': False,
					'test': [15]
				}]
			}, {
				'id': 1,
				'code': 'python',
				'description': 'class',
				'pattern': [{
					'required': True,
					'specific': True,
					'ifLast': False,
					'test': ['class']
				}, {
					'required': True,
					'specific': False,
					'ifLast': False,
					'test': ['abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-']
				}, {
					'required': True,
					'specific': True,
					'ifLast': False,
					'test': [15]
				}]
			}, {
				'id': 2,
				'code': 'python',
				'description': 'variable',
				'pattern': [{
					'required': True,
					'specific': False,
					'ifLast': False,
					'test': ['abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-.']
				}, {
					'required': True,
					'specific': True,
					'ifLast': False,
					'test': [13]
				}, {
					'required': True,
					'specific': False,
					'ifLast': False,
					'test': [0, 2, 4, 12, 11, 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-.']
				}]
			}, {
				'id': 3,
				'code': 'python',
				'description': 'variable',
				'pattern': [{
					'required': False,
					'specific': True,
					'ifLast': False,
					'test': ['var']
				}, {
					'required': True,
					'specific': False,
					'ifLast': False,
					'test': ['abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-.']
				}, {
					'required': True,
					'specific': True,
					'ifLast': False,
					'test': [13]
				}, {
					'required': True,
					'specific': False,
					'ifLast': False,
					'test': [0, 2, 4, 12, 11, ['quote'], 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-.']
				}, {
					'required': True,
					'specific': True,
					'ifLast': False,
					'test': [14]
				}]
			}, {
				'id': 4,
				'code': 'javascript',
				'description': 'function',
				'pattern': [{
					'required': True,
					'specific': True,
					'ifLast': False,
					'test': ['function']
				}, {
					'required': True,
					'specific': False,
					'ifLast': False,
					'test': ['abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-']
				}, {
					'required': True,
					'specific': True,
					'ifLast': False,
					'test': [2]
				}, {
					'required': True,
					'specific': True,
					'ifLast': False,
					'test': [4]
				}]
			}, {
				'id': 5,
				'code': 'python',
				'description': 'import',
				'pattern': [{
					'required': True,
					'specific': True,
					'ifLast': False,
					'test': ['import']
				}, {
					'required': True,
					'specific': False,
					'ifLast': False,
					'test': ['abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-.']
				}, {
					'required': False,
					'specific': False,
					'test': ['as']
				}, {
					'required': False,
					'specific': False,
					'ifLast': True,
					'test': ['abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-.']
				}]
			}, {
				'id': 6,
				'code': 'python',
				'description': 'variable',
				'pattern': [{
					'required': True,
					'specific': False,
					'ifLast': False,
					'test': [0, 2, 4, 12, 11]
				}]
			}, {
				'id': 7,
				'code': 'python',
				'description': 'variable',
				'pattern': [{
					'required': True,
					'specific': False,
					'ifLast': False,
					'test': ['abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-.']
				}, {
					'required': True,
					'specific': False,
					'ifLast': False,
					'test': [2]
				}]
		}]
}



